/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;
import java.awt.Color;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class serverfinal extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form serverfinal
     */
    private ObjectInputStream input;
    private ObjectOutputStream output;
    public serverfinal() {
        initComponents();
        Thread t= new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Server Tic Tac Toe  'O'");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String val1 = jTextField1.getText();
        String val2 = jTextField2.getText();
        String val3 = jTextField3.getText();
        String val4 = jTextField4.getText();
        String val5 = jTextField5.getText();
        String val7 = jTextField7.getText();
        String val9 = jTextField9.getText();

        if (val1.equals("o") && val2.equals("o") && val3.equals("o")) {
            jTextField1.setBackground(Color.red);
            jTextField2.setBackground(Color.red);
            jTextField3.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
           
            jTextField1.setBackground(Color.white);
            jTextField2.setBackground(Color.white);
            jTextField3.setBackground(Color.white);
           
        } else if (val1.equals("x") && val2.equals("x") && val3.equals("x")) {
            jTextField1.setBackground(Color.red);
            jTextField2.setBackground(Color.red);
            jTextField3.setBackground(Color.red);
           
           
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setBackground(Color.white);
            jTextField2.setBackground(Color.white);
            jTextField3.setBackground(Color.white);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
        } else if (val1.equals("o") && val4.equals("o") && val7.equals("o")) {
            jTextField1.setBackground(Color.red);
            jTextField4.setBackground(Color.red);
            jTextField7.setBackground(Color.red);
           
            JOptionPane.showMessageDialog(this, "o player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField4.setBackground(Color.white);
            jTextField7.setBackground(Color.white);
        } else if (val1.equals("x") && val4.equals("x") && val7.equals("x")) {
            jTextField1.setBackground(Color.red);
            jTextField4.setBackground(Color.red);
            jTextField7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField4.setBackground(Color.white);
            jTextField7.setBackground(Color.white);
        } else if (val1.equals("o") && val5.equals("o") && val9.equals("o")) {
            jTextField1.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
           
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
           
        } else if (val1.equals("x") && val5.equals("x") && val9.equals("x")) {
            jTextField1.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
         String val1 = jTextField1.getText();
        String val2 = jTextField2.getText();
        String val3 = jTextField3.getText();
        String val5 = jTextField5.getText();
        String val8 = jTextField8.getText();

        if (val1.equals("o") && val2.equals("o") && val3.equals("o")) {
            jTextField1.setBackground(Color.red);
            jTextField2.setBackground(Color.red);
            jTextField3.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField2.setBackground(Color.white);
            jTextField3.setBackground(Color.white);
        } else if (val1.equals("x") && val2.equals("x") && val3.equals("x")) {
            jTextField1.setBackground(Color.red);
            jTextField2.setBackground(Color.red);
            jTextField3.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField2.setBackground(Color.white);
            jTextField3.setBackground(Color.white);
        } else if (val2.equals("o") && val5.equals("o") && val8.equals("o")) {
            jTextField2.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField8.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField2.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField8.setBackground(Color.white);
        } else if (val2.equals("x") && val5.equals("x") && val8.equals("x")) {
            jTextField2.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField8.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField2.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField8.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
           String val1 = jTextField1.getText();
        String val2 = jTextField2.getText();
        String val3 = jTextField3.getText();
        String val5 = jTextField5.getText();
        String val6 = jTextField6.getText();
        String val7 = jTextField7.getText();
        String val9 = jTextField9.getText();

        if (val1.equals("o") && val2.equals("o") && val3.equals("o")) {
            jTextField1.setBackground(Color.red);
            jTextField2.setBackground(Color.red);
            jTextField3.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField2.setBackground(Color.white);
            jTextField3.setBackground(Color.white);
        } else if (val1.equals("x") && val2.equals("x") && val3.equals("x")) {
            jTextField1.setBackground(Color.red);
            jTextField2.setBackground(Color.red);
            jTextField3.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField2.setBackground(Color.white);
            jTextField3.setBackground(Color.white);
        } else if (val3.equals("o") && val6.equals("o") && val9.equals("o")) {
            jTextField3.setBackground(Color.red);
            jTextField6.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField3.setBackground(Color.white);
            jTextField6.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        } else if (val3.equals("x") && val6.equals("x") && val9.equals("x")) {
            jTextField3.setBackground(Color.red);
            jTextField6.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField3.setBackground(Color.white);
            jTextField6.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        } else if (val3.equals("o") && val5.equals("o") && val7.equals("o")) {
           
            jTextField3.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
           
            jTextField3.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField7.setBackground(Color.white);
           
        } else if (val3.equals("x") && val5.equals("x") && val7.equals("x")) {
            jTextField3.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField3.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField7.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
         String val1 = jTextField1.getText();
        String val4 = jTextField4.getText();
        String val5 = jTextField5.getText();
        String val6 = jTextField6.getText();
        String val7 = jTextField7.getText();

        if (val1.equals("o") && val4.equals("o") && val7.equals("o")) {
            jTextField1.setBackground(Color.red);
            jTextField4.setBackground(Color.red);
            jTextField7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField4.setBackground(Color.white);
            jTextField7.setBackground(Color.white);
        } else if (val1.equals("x") && val4.equals("x") && val7.equals("x")) {
            jTextField1.setBackground(Color.red);
            jTextField4.setBackground(Color.red);
            jTextField7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField4.setBackground(Color.white);
            jTextField7.setBackground(Color.white);
        } else if (val4.equals("o") && val5.equals("o") && val6.equals("o")) {
            jTextField4.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField6.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField4.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField6.setBackground(Color.white);
        } else if (val4.equals("x") && val5.equals("x") && val6.equals("x")) {
            jTextField4.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField6.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField4.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField6.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        // TODO add your handling code here:
        // TODO add your handling code here:
        String val1 = jTextField1.getText();
        String val2 = jTextField2.getText();
        String val3 = jTextField3.getText();
        String val4 = jTextField4.getText();
        String val5 = jTextField5.getText();
        String val6 = jTextField6.getText();
        String val7 = jTextField7.getText();
        String val8 = jTextField8.getText();
        String val9 = jTextField9.getText();

        if (val4.equals("o") && val5.equals("o") && val6.equals("o")) {
            jTextField4.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField6.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
           
            jTextField4.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField6.setBackground(Color.white);
        } else if (val4.equals("x") && val5.equals("x") && val6.equals("x")) {
            jTextField4.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField6.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
           
            jTextField4.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField6.setBackground(Color.white);
        } else if (val2.equals("o") && val5.equals("o") && val8.equals("o")) {
            jTextField2.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField8.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField2.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField8.setBackground(Color.white);
        } else if (val2.equals("x") && val5.equals("x") && val8.equals("x")) {
        jTextField2.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField8.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField2.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField8.setBackground(Color.white);
        } else if (val1.equals("o") && val5.equals("o") && val9.equals("o")) {
            jTextField1.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "0 Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        } else if (val1.equals("x") && val5.equals("x") && val9.equals("x")) {
            jTextField1.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        } else if (val3.equals("o") && val5.equals("o") && val7.equals("o")) {
            jTextField3.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField3.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField7.setBackground(Color.white);
        } else if (val3.equals("x") && val5.equals("x") && val7.equals("x")) {
            jTextField3.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField3.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField7.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // TODO add your handling code here:
         // TODO add your handling code here:
        String val1 = jTextField1.getText();
        String val2 = jTextField2.getText();
        String val3 = jTextField3.getText();
        String val4 = jTextField4.getText();
        String val5 = jTextField5.getText();
        String val6 = jTextField6.getText();
        String val7 = jTextField7.getText();
        String val8 = jTextField8.getText();
        String val9 = jTextField9.getText();

        if (val4.equals("o") && val5.equals("o") && val6.equals("o")) {
            jTextField4.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField6.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o player  Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField4.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField6.setBackground(Color.white);
        } else if (val4.equals("x") && val5.equals("x") && val6.equals("x")) {
            jTextField4.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField6.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField4.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField6.setBackground(Color.white);
        } else if (val3.equals("o") && val6.equals("o") && val9.equals("o")) {
            jTextField3.setBackground(Color.red);
            jTextField6.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
           
            jTextField3.setBackground(Color.white);
            jTextField6.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        } else if (val3.equals("x") && val6.equals("x") && val9.equals("x")) {
            jTextField3.setBackground(Color.red);
            jTextField6.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField3.setBackground(Color.white);
            jTextField6.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String val1 = jTextField1.getText();
        String val2 = jTextField2.getText();
        String val3 = jTextField3.getText();
        String val4 = jTextField4.getText();
        String val5 = jTextField5.getText();
        String val6 = jTextField6.getText();
        String val7 = jTextField7.getText();
        String val8 = jTextField8.getText();
        String val9 = jTextField9.getText();

        if (val1.equals("o") && val4.equals("o") && val7.equals("o")) {
            jTextField1.setBackground(Color.red);
            jTextField4.setBackground(Color.red);
            jTextField7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField4.setBackground(Color.white);
            jTextField7.setBackground(Color.white);
        } else if (val1.equals("x") && val4.equals("x") && val7.equals("x")) {
            jTextField1.setBackground(Color.red);
            jTextField4.setBackground(Color.red);
            jTextField7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField4.setBackground(Color.white);
            jTextField7.setBackground(Color.white);
        } else if (val7.equals("o") && val8.equals("o") && val9.equals("o")) {
            jTextField7.setBackground(Color.red);
            jTextField8.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField7.setBackground(Color.white);
            jTextField8.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        } else if (val7.equals("x") && val8.equals("x") && val9.equals("x")) {
            jTextField7.setBackground(Color.red);
            jTextField8.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
           
            jTextField7.setBackground(Color.white);
            jTextField8.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        } else if (val3.equals("o") && val5.equals("o") && val7.equals("o")) {
            jTextField3.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField3.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField7.setBackground(Color.white);
        } else if (val3.equals("x") && val5.equals("x") && val7.equals("x")) {
            jTextField3.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField3.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField7.setBackground(Color.white);
        }
             sendPosition(7);

    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
         String val1 = jTextField1.getText();
        String val2 = jTextField2.getText();
        String val3 = jTextField3.getText();
        String val4 = jTextField4.getText();
        String val5 = jTextField5.getText();
        String val6 = jTextField6.getText();
        String val7 = jTextField7.getText();
        String val8 = jTextField8.getText();
        String val9 = jTextField9.getText();

        if (val2.equals("o") && val5.equals("o") && val8.equals("o")) {
            jTextField2.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField8.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
           
            jTextField2.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField8.setBackground(Color.white);
        } else if (val2.equals("x") && val5.equals("x") && val8.equals("x")) {
            jTextField2.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField8.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField2.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField8.setBackground(Color.white);
        } else if (val7.equals("o") && val8.equals("o") && val9.equals("o")) {
            jTextField7.setBackground(Color.red);
            jTextField8.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField7.setBackground(Color.white);
            jTextField8.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        } else if (val7.equals("x") && val8.equals("x") && val9.equals("x")) {
            jTextField7.setBackground(Color.red);
            jTextField8.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField7.setBackground(Color.white);
            jTextField8.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        }
             sendPosition(8);

    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
           String val1 = jTextField1.getText();
        String val2 = jTextField2.getText();
        String val3 = jTextField3.getText();
        String val4 = jTextField4.getText();
        String val5 = jTextField5.getText();
        String val6 = jTextField6.getText();
        String val7 = jTextField7.getText();
        String val8 = jTextField8.getText();
        String val9 = jTextField9.getText();
       

        if (val1.equals("o") && val5.equals("o") && val9.equals("o")) {
            jTextField1.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player  Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        } else if (val1.equals("x") && val5.equals("x") && val9.equals("x")) {
            jTextField1.setBackground(Color.red);
            jTextField5.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField1.setBackground(Color.white);
            jTextField5.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        } else if (val7.equals("o") && val8.equals("o") && val9.equals("o")) {
            jTextField7.setBackground(Color.red);
            jTextField8.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField7.setBackground(Color.white);
            jTextField8.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        } else if (val7.equals("x") && val8.equals("x") && val9.equals("x")) {
            jTextField7.setBackground(Color.red);
            jTextField8.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField7.setBackground(Color.white);
            jTextField8.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        } else if (val3.equals("o") && val6.equals("o") && val9.equals("o")) {
            jTextField3.setBackground(Color.red);
            jTextField6.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "o player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField3.setBackground(Color.white);
            jTextField6.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        } else if (val3.equals("x") && val6.equals("x") && val9.equals("x")) {
            jTextField3.setBackground(Color.red);
            jTextField6.setBackground(Color.red);
            jTextField9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "x Player Win");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField3.setBackground(Color.white);
            jTextField6.setBackground(Color.white);
            jTextField9.setBackground(Color.white);
        }
             sendPosition(9);

    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
             sendPosition(6);

    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
             sendPosition(5);

    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
             sendPosition(4);

    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
             sendPosition(3);

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
             sendPosition(2);

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
             sendPosition(1);

    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(serverfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(serverfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(serverfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(serverfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new serverfinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
      try
        {
            ServerSocket server = new ServerSocket(9000);
           // jTextField1.setText("Waiting for connection");
            Socket connection=server.accept(); //waits for client request to accept it ! , create socket to connect with the client
            output =new ObjectOutputStream(connection.getOutputStream());

            input=new ObjectInputStream(connection.getInputStream());

            
         //  output.writeObject("SERVER>>>>Connection successful");

            
            processClientMessages();                                                                                 
        }
        catch (IOException e)
        {
        JOptionPane.showMessageDialog(null, e.getMessage(),"Fatal Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void processClientMessages() {
        try
        {
            while (true)
            {
                int message=(int)input.readObject();

              
                switch(message){
                    case 1:
                        jTextField1.setText("x");
                        break;
                    case 2:
                        jTextField2.setText("x");
                        break;
                    case 3:
                        jTextField3.setText("x");
                        break;
                    case 4:
                        jTextField4.setText("x");
                        break;
                    case 5:
                        jTextField5.setText("x");
                        break;
                    case 6:
                        jTextField6.setText("x");
                        break;
                    case 7:
                        jTextField7.setText("x");
                        break;
                    case 8:
                        jTextField8.setText("x");
                        break;
                    case 9:
                        jTextField9.setText("x");
                        break;
                }

          
                //jTextArea1.append(message);                
            }
    
        
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Fatal Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    void sendPosition(int pos) {

        try {
            output.writeObject(/*"\nCLIENT>>>"+*/pos);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Fatal Error", JOptionPane.ERROR_MESSAGE);
        }

    }
}
